CREATE TABLE "user_predictions_snapshots" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"round_id" uuid NOT NULL,
	"wallet_address" varchar(44) NOT NULL,
	"top_performer_1" varchar(10),
	"top_performer_2" varchar(10),
	"top_performer_3" varchar(10),
	"top_performer_4" varchar(10),
	"top_performer_5" varchar(10),
	"top_performer_1_timestamp" bigint,
	"top_performer_2_timestamp" bigint,
	"top_performer_3_timestamp" bigint,
	"top_performer_4_timestamp" bigint,
	"top_performer_5_timestamp" bigint,
	"worst_performer_1" varchar(10),
	"worst_performer_2" varchar(10),
	"worst_performer_3" varchar(10),
	"worst_performer_4" varchar(10),
	"worst_performer_5" varchar(10),
	"worst_performer_1_timestamp" bigint,
	"worst_performer_2_timestamp" bigint,
	"worst_performer_3_timestamp" bigint,
	"worst_performer_4_timestamp" bigint,
	"worst_performer_5_timestamp" bigint,
	"points" bigint DEFAULT 0 NOT NULL,
	"last_updated" bigint,
	"snapshot_timestamp" timestamp NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL
);
